# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{stopwords-filter}
  s.version = "0.7.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["David J. Brenes"]
  s.date = %q{2021-12-19}
  s.description = %q{Small library that allows you to create a simple stopwords filter or use some based on Snowball stopwords lists}
  s.email = %q{davidjbrenes@gmail.com}
  s.extra_rdoc_files = [
    "CHANGELOG",
    "LICENSE.txt",
    "README.md"
  ]
  locale_files = []
  Dir.glob("lib/stopwords/snowball/locales/*.csv") do |locale_file|
    locale_files << locale_file
  end
  s.files = [
    "CHANGELOG",
    "Gemfile",
    "Gemfile.lock",
    "README.md",
    "VERSION",
    "lib/stopwords.rb",
    "lib/stopwords/filter.rb",
    "lib/stopwords/snowball.rb",
    "lib/stopwords/snowball/filter.rb",
    "lib/stopwords/snowball/wordsieve.rb",
    "spec/lib/filter_spec.rb",
    "spec/lib/snowball_filter_spec.rb",
    "spec/spec_helper.rb"
  ] + locale_files
  s.homepage = %q{http://github.com/brenes/stopwords-filter}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.2}
  s.summary = %q{Snowball based filters for stopwords}

end

